---
- name: link dotfiles
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "~/.dotfiles/bash_profile", dest: "~/.bash_profile"}
    - { src: "~/.dotfiles/bashrc", dest: "~/.bashrc"}
    - { src: "~/.dotfiles/config/fish/config.fish", dest: "~/.config/fish/config.fish"}
    - { src: "~/.dotfiles/tmux.conf", dest: "~/.tmux.conf"}
    - { src: "~/.dotfiles/vimrc", dest: "~/.vimrc"}
    - { src: "~/.dotfiles/zshrc", dest: "~/.zshrc"}
    - { src: "~/.dotfiles/gitconfig", dest: "~/.gitconfig"}
