---
- name: Include APT package list
  include_vars: vars/apt.yml
  tags:
    - apt

- block:
  - name: Update/Upgrade apt
    apt:
      update_cache: true
      upgrade: dist

  - name: Manage apt packages
    apt:
      name: "{{ item.key }}"
      state: "{{ item.value.state | default('latest') }}"
    with_dict: "{{apt}}"

  become: yes
  become_user: root
  become_method: sudo
  when: ansible_os_family == "Debian"
  tags: apt