- name: Add ruby plugin
  command: "asdf plugin-add ruby"
  register: ruby_add
  failed_when: ruby_add == 2

- name: "Install ruby versions"
  command: asdf install ruby {{item}}
  loop: "{{ruby_versions}}"

- name: Set global version for ruby to {{ruby_versions[1]}}
  command: "asdf global ruby {{ruby_versions[0]}}"
